In [1]:
# Import Required Libraries
import pandas as pd

In [6]:
# Load one of the weather data files
weather = pd.read_json('/Users/davidosullivan/Desktop/ATU_DataAnalytics_Semester2/Semester2_Repositories/computer_infrastructure_assessment/data/weather/weather.json')

# Ensure it loads properly
weather.head()

,name,temperature,symbol,weatherDescription,text,windSpeed,windGust,cardinalWindDirection,windDirection,humidity,rainfall,pressure,dayName,date,reportTime
0,Athenry,3,04n,Cloudy,"""Cloudy""",6,-,N,0,86,0,1038,Wednesday,2024-11-12,00:00
1,Athenry,3,04n,Cloudy,"""Cloudy""",7,-,N,0,85,0,1037,Wednesday,2024-11-12,01:00
2,Athenry,3,04n,Cloudy,"""Cloudy""",6,-,NE,45,86,0,1037,Wednesday,2024-11-12,02:00
3,Athenry,3,04n,Cloudy,"""Cloudy""",6,-,NE,45,87,0,1037,Wednesday,2024-11-12,03:00
4,Athenry,2,04n,Cloudy,"""Cloudy""",6,-,NE,45,89,0,1036,Wednesday,2024-11-12,04:00

In [7]:
weather.describe()

,temperature,windSpeed,windDirection,humidity,rainfall,pressure,date
count,18.000000,18.000000,18.000000,18.000000,18.0,18.000000,18
mean,3.722222,5.833333,55.000000,83.166667,0.0,1036.277778,2024-11-12 00:00:00
min,2.000000,2.000000,0.000000,75.000000,0.0,1035.000000,2024-11-12 00:00:00
25%,3.000000,6.000000,45.000000,80.250000,0.0,1036.000000,2024-11-12 00:00:00
50%,3.000000,6.000000,45.000000,83.500000,0.0,1036.000000,2024-11-12 00:00:00
75%,5.000000,6.000000,90.000000,86.000000,0.0,1037.000000,2024-11-12 00:00:00
max,5.000000,9.000000,135.000000,89.000000,0.0,1038.000000,2024-11-12 00:00:00
std,1.017815,1.424574,36.380344,3.929526,0.0,0.894792,NaN

In [8]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   18 non-null     object
 1   temperature            18 non-null     int64
 2   symbol                 18 non-null     object
 3   weatherDescription     18 non-null     object
 4   text                   18 non-null     object
 5   windSpeed              18 non-null     int64
 6   windGust               18 non-null     object
 7   cardinalWindDirection  18 non-null     object
 8   windDirection          18 non-null     int64
 9   humidity               18 non-null     int64
 10  rainfall               18 non-null     int64
 11  pressure               18 non-null     int64
 12  dayName                18 non-null     object
 13  date                   18 non-null     datetime64[ns]
 14  reportTime             18 non-null     object
dtypes: datetime64[ns](1), int64(6), object(8)
memory usage: 2.2+ KB